import pandas as pd
import random

british_cities = [
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'Coventry', 'Nottingham', 'Leicester', 'Newcastle upon Tyne',
    'Bradford', 'Stoke-on-Trent', 'Wolverhampton', 'Derby', 'Sunderland', 'Reading', 'Luton',
    'Dundee', 'Belfast', 'Swansea', 'Southampton', 'Hull', 'Kingston upon Hull', 'Blackpool',
    'Middlesbrough', 'Woking', 'Gillingham', 'Southend-on-Sea', 'Wakefield', 'Oxford', 'Cambridge',
    'York', 'Norwich', 'Basingstoke', 'Guildford', 'Ipswich', 'Rochdale', 'Crawley', 'Telford', 
    'Slough', 'Warrington', 'Stockport', 'Basingstoke', 'Chelmsford', 'Poole', 'Swindon', 'Eastbourne',
    'Hastings', 'Blackburn', 'Dartford', 'Newport', 'Wokingham', 'Telford', 'Bexley', 'Croydon', 
    'Basingstoke', 'Rugby', 'Bromley', 'Hounslow', 'Farnborough', 'Basingstoke', 'Redcar', 'Sutton',
    'Hertford', 'Maidenhead', 'Tunbridge Wells', 'Harrogate', 'Woking', 'Eastleigh', 'Camberley',
    'Crawley', 'Stockport', 'Chester', 'Truro', 'Lichfield', 'Worcester', 'Bedford', 'Hove', 
    'Folkestone', 'Maidstone', 'Darlington', 'Clacton-on-Sea', 'Altrincham', 'Weymouth', 'Bracknell',
    
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool',
    
    'london', 'Manchestar', 'Birrmingham', 'Glasglow', 'liverpool', 'leed', 'Edinbrugh',
    'Sheffied', 'Bristl', 'cardiff', 'Notinham', 'Cambrige', 'Ipswhich', 'Stockprt', 'Maidston',
    'londno', 'londn', 'Londn',  'manchester', 'manchestr', 'birmingham', 'glasgow', 'liverpol', 'Liverpol',
    
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'Coventry', 'Nottingham', 'Leicester', 'Newcastle upon Tyne',
    'Bradford', 'Stoke-on-Trent', 'Wolverhampton', 'Derby', 'Sunderland', 'Reading', 'Luton',
    'Dundee', 'Belfast', 'Swansea', 'Southampton', 'Hull', 'Kingston upon Hull', 'Blackpool',
    'Middlesbrough', 'Woking', 'Gillingham', 'Southend-on-Sea', 'Wakefield', 'Oxford', 'Cambridge',
    'York', 'Norwich', 'Basingstoke', 'Guildford', 'Ipswich', 'Rochdale', 'Crawley', 'Telford', 
    'Slough', 'Warrington', 'Stockport', 'Basingstoke', 'Chelmsford', 'Poole', 'Swindon', 'Eastbourne',
    'Hastings', 'Blackburn', 'Dartford', 'Newport', 'Wokingham', 'Telford', 'Bexley', 'Croydon', 
    'Basingstoke', 'Rugby', 'Bromley', 'Hounslow', 'Farnborough', 'Basingstoke', 'Redcar', 'Sutton',
    'Hertford', 'Maidenhead', 'Tunbridge Wells', 'Harrogate', 'Woking', 'Eastleigh', 'Camberley',
    'Crawley', 'Stockport', 'Chester', 'Truro', 'Lichfield', 'Worcester', 'Bedford', 'Hove', 
    'Folkestone', 'Maidstone', 'Darlington', 'Clacton-on-Sea', 'Altrincham', 'Weymouth', 'Bracknell',
    
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool',
    
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'Coventry', 'Nottingham', 'Leicester', 'Newcastle upon Tyne',
    'Bradford', 'Stoke-on-Trent', 'Wolverhampton', 'Derby', 'Sunderland', 'Reading', 'Luton',
    'Dundee', 'Belfast', 'Swansea', 'Southampton', 'Hull', 'Kingston upon Hull', 'Blackpool',
    'Middlesbrough', 'Woking', 'Gillingham', 'Southend-on-Sea', 'Wakefield', 'Oxford', 'Cambridge',
    'York', 'Norwich', 'Basingstoke', 'Guildford', 'Ipswich', 'Rochdale', 'Crawley', 'Telford', 
    'Slough', 'Warrington', 'Stockport', 'Basingstoke', 'Chelmsford', 'Poole', 'Swindon', 'Eastbourne',
    'Hastings', 'Blackburn', 'Dartford', 'Newport', 'Wokingham', 'Telford', 'Bexley', 'Croydon', 
    'Basingstoke', 'Rugby', 'Bromley', 'Hounslow', 'Farnborough', 'Basingstoke', 'Redcar', 'Sutton',
    'Hertford', 'Maidenhead', 'Tunbridge Wells', 'Harrogate', 'Woking', 'Eastleigh', 'Camberley',
    'Crawley', 'Stockport', 'Chester', 'Truro', 'Lichfield', 'Worcester', 'Bedford', 'Hove', 
    'Folkestone', 'Maidstone', 'Darlington', 'Clacton-on-Sea', 'Altrincham', 'Weymouth', 'Bracknell',
    
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
    'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh',
    'Sheffield', 'Bristol', 'Cardiff', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 
    'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London', 'London',
    'London', 'London', 'London', 'London', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester',
    'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 
    'Manchester', 'Manchester','Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 
    'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 
    'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Birmingham', 'Glasgow', 'Liverpool', 'Liverpool',
    'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool',
]

df = pd.read_csv("accidents_no_cities.csv")

rows_num = df.shape[0]

cities_column = []

for i in range(rows_num):
    cities_column.append(random.choice(british_cities))
    
df.insert(1, 'City', cities_column)

df.drop(['Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude', 'Latitude'], axis=1, inplace=True)

df.to_csv('accidents_2012_to_2014.csv', index=False)